# Generated by Django 3.1.5 on 2021-01-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leasetransaction',
            options={'ordering': ('-txn_date',)},
        ),
    ]
