# Generated by Django 3.1.5 on 2021-01-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20210124_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leasehistory',
            options={'verbose_name_plural': 'Lease histories'},
        ),
    ]
