# Generated by Django 3.1.5 on 2021-01-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20210124_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaselisting',
            name='lease_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaselisting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=6),
        ),
    ]
