# Generated by Django 3.1.5 on 2021-01-24 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0006_auto_20210124_1313'),
        ('marketplace', '0006_auto_20210124_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaselisting',
            name='lease',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='shortcodes.shortcodelease'),
        ),
    ]
