# Generated by Django 3.1.5 on 2021-01-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0006_auto_20210124_1313'),
        ('marketplace', '0007_auto_20210124_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaselisting',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='shortcodes.shortcodelease'),
        ),
        migrations.AddConstraint(
            model_name='leaselisting',
            constraint=models.UniqueConstraint(condition=models.Q(is_active=True), fields=('lease',), name='unique_active_lease_listing'),
        ),
    ]
