# Generated by Django 3.1.5 on 2021-01-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='shortcodelease',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
