# Generated by Django 3.1.5 on 2021-01-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0003_auto_20210123_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcodelease',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
