# Generated by Django 3.1.5 on 2021-01-24 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0004_auto_20210123_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcodelease',
            name='shortcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='shortcodes.shortcode'),
        ),
    ]
