# Generated by Django 3.1.5 on 2021-01-24 18:13

from django.db import migrations, models
import smisher.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0005_auto_20210123_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcodelease',
            name='expires_at',
            field=models.DateTimeField(default=smisher.utils.get_default_expiration),
        ),
    ]
