# Generated by Django 3.1.5 on 2021-01-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('cust_name',)},
        ),
    ]
